version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine

  app:
    build: .
    command: node index.js
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    # ADD THIS BLOCK
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: node worker.js
    volumes:
      - .:/app
    env_file:
      - .env
    # ADD THIS BLOCK
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - db

volumes:
  postgres_data: